/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Monkey.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from '../../src/components/AugmentedReality/contexts/CharacterAnimations';
import { useEffect } from 'react';
export default function Monkey(props) {
  const { nodes, materials } = useGLTF('/models//Monkey.gltf')


      const {setAnimations} = useCharacterAnimations();
      useEffect(() => {
        setAnimations([]);
      }, [setAnimations]);
    
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[0, 1.112, 0]} scale={0.099} />
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[0, 0.898, -0.104]} rotation={[-Math.PI / 2, 0, 0]} scale={0.023} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[0.597, 0.577, 0.043]} rotation={[0, 0, -1.165]} scale={0.022} />
      <mesh geometry={nodes.Plane.geometry} material={nodes.Plane.material} />
      <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} position={[0.004, 1.566, -0.058]} scale={0.246} />
    </group>
  )
}

useGLTF.preload('/models/Monkey.gltf')
