/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Panda.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useCharacterAnimations } from '../../src/components/AugmentedReality/contexts/CharacterAnimations'
import { useEffect } from 'react'


export default function Panda(props) {
  const { nodes, materials } = useGLTF('/models/Panda.gltf')

      const {setAnimations} = useCharacterAnimations();
        useEffect(() => {
          setAnimations([]);
        }, [setAnimations]);
      
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} />
    </group>
  )
}

useGLTF.preload('/models/Panda.gltf')
