/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 5ton_AC.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react'
import { useCharacterAnimations } from '../../../src/AugmentedReality/contexts/CharacterAnimations'

export default function Model(props) {
  const { nodes, materials } = useGLTF('models/oldModels/5ton_AC.gltf')

   const {setAnimations} = useCharacterAnimations();
              useEffect(() => {
                setAnimations([]);
              }, [setAnimations]);
  return (
    <group {...props} dispose={null} scale={0.1}>
      <group position={[0, 9.466, 0]}>
        <mesh geometry={nodes.Cube001_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Cube001_2.geometry} material={materials['Material.003']} />
      </group>
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[0, 9.466, -0.048]} scale={1.001} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.001']} position={[-0.005, 18.192, 1.556]} />
      <mesh geometry={nodes['steel-grill'].geometry} material={materials['steel-grill']} position={[0, 3.14, 1.762]} rotation={[Math.PI / 2, 0, 0]} scale={[4.994, 8.019, 3.018]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0, 17.128, 1.617]} scale={[1.017, 1.034, 1]} />
    </group>
  )
}

useGLTF.preload('models/oldModels/5ton_AC.gltf')
